version: 2
updates:
  - package-ecosystem: npm # covers pnpm workspaces
    directory: "/"
    schedule:
      interval: weekly
    groups:
      npm-non-major:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      npm-major:
        update-types:
          - "major"
        patterns:
          - "*"
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions-non-major:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      github-actions-major:
        update-types:
          - "major"
        patterns:
          - "*"
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
